// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hhc-hero/AnimatedHero.tsx": () => import("../components/mockups/hhc-hero/AnimatedHero.tsx"),
  "./components/mockups/section-bg/GrainTexture.tsx": () => import("../components/mockups/section-bg/GrainTexture.tsx"),
  "./components/mockups/section-bg/SteamWisps.tsx": () => import("../components/mockups/section-bg/SteamWisps.tsx")
};
